# Generated by Django 4.0.5 on 2022-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de cliente'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_detalle_venta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del detalle de venta'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='id_medio_pago',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del medio de pago'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la venta'),
        ),
    ]
